version: "3.8"
networks:
  kafka-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
services:
  kafka01:
    container_name: kafka01
    image: jin-kafka:3.3.1
    build: 
      context: docker-build
    ports:
        - 29192:29192
    dns:
      - 8.8.8.8
      - 4.4.4.4
    restart: always
    volumes:
      - ./config/kafka01/server.properties:/kafka/config/kraft/server.properties
      - data_kafka_01:/kafka-data/kraft-combined-logs
    networks:
      kafka-net:
        ipv4_address: 10.0.0.11

  kafka02:
    container_name: kafka02
    image: jin-kafka:3.3.1
    build: 
      context: docker-build
    ports:
        - 29292:29292
    dns:
      - 8.8.8.8
      - 4.4.4.4        
    restart: always
    volumes:
      - ./config/kafka02/server.properties:/kafka/config/kraft/server.properties
      - data_kafka_02:/kafka-data/kraft-combined-logs
    networks:
      kafka-net:
        ipv4_address: 10.0.0.12

  kafka03:
    container_name: kafka03
    image: jin-kafka:3.3.1
    build: 
      context: docker-build
    ports:
        - 29392:29392
    dns:
      - 8.8.8.8
      - 4.4.4.4
    restart: always

    volumes:
      - ./config/kafka03/server.properties:/kafka/config/kraft/server.properties
      - data_kafka_03:/kafka-data/kraft-combined-logs
    networks:
      kafka-net:
        ipv4_address: 10.0.0.13
  kafkadrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "127.0.0.1:9000:9000"
    restart: always
    environment:
      - KAFKA_BROKERCONNECT=kafka01:9092,kafka02:9092,kafka03:9092
      - JAVA_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    networks:
      - kafka-net


  kafka-kouncil:
    image: consdata/kouncil:1.4
    container_name: kafka-kouncil
    ports:
      - "8084:8080"
    restart: always
    environment:
      - BOOTSTRAPSERVERS=kafka01:9092,kafka02:9092,kafka03:9092
    networks:
      - kafka-net


volumes:
  data_kafka_01:
  data_kafka_02:
  data_kafka_03: